name: PHPCS Lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install PHPCS
        run: |
          composer global require "squizlabs/php_codesniffer=*"

      - name: Run phpcs
        run: ~/.composer/vendor/bin/phpcs --standard=phpcs.xml .
        
      - name: Upload PHPCS results (optional)
        if: failure()
        run: |
          ~/.composer/vendor/bin/phpcs --report=summary > phpcs.txt
